# Generated by Django 4.1.7 on 2023-02-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Item_info', models.CharField(default='', max_length=150)),
                ('Description', models.CharField(default='', max_length=150)),
                ('Location', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_info', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(default=0)),
                ('branch', models.CharField(default='Dorset College', max_length=20)),
                ('year', models.CharField(default='First Year', max_length=20)),
                ('phone_no', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
