# Generated by Django 4.1.7 on 2023-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='the_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
