# Generated by Django 4.1.7 on 2023-03-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_itemdata_the_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='the_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
