# Generated by Django 4.1.7 on 2023-03-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_requestinfo_the_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemData',
        ),
    ]
