# Generated by Django 4.1.7 on 2023-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_delete_itemdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
