# Generated by Django 4.1.7 on 2023-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_requestinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
