# Generated by Django 4.1.7 on 2023-03-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_claim_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
